/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package s.calculadora;

/**
 *
 * @author alanb
 */
public class calculadora extends javax.swing.JFrame {

    /**
     * Creates new form calculadora
     */
    public calculadora() {
        initComponents();
        disableHex();
        flag = 1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrp_Sistema = new javax.swing.ButtonGroup();
        btn_0 = new javax.swing.JButton();
        btn_1 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_7 = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        btn_9 = new javax.swing.JButton();
        btn_A = new javax.swing.JButton();
        btn_C = new javax.swing.JButton();
        btn_B = new javax.swing.JButton();
        btn_D = new javax.swing.JButton();
        btn_E = new javax.swing.JButton();
        btn_F = new javax.swing.JButton();
        btn_Equal = new javax.swing.JButton();
        btn_Clear = new javax.swing.JButton();
        btn_division = new javax.swing.JButton();
        btn_multiplicacion = new javax.swing.JButton();
        btn_resta = new javax.swing.JButton();
        btn_Suma = new javax.swing.JButton();
        lbl_Dec = new javax.swing.JLabel();
        lbl_Bin = new javax.swing.JLabel();
        lbl_Oct = new javax.swing.JLabel();
        lbl_Hex = new javax.swing.JLabel();
        rBtn_Dec = new javax.swing.JRadioButton();
        rBtn_Hex = new javax.swing.JRadioButton();
        rBtn_Oct = new javax.swing.JRadioButton();
        rBtn_Bin = new javax.swing.JRadioButton();
        lbl_resultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora - By KennyBG");
        setMaximumSize(new java.awt.Dimension(341, 560));
        setMinimumSize(new java.awt.Dimension(341, 560));
        setPreferredSize(new java.awt.Dimension(341, 560));
        setSize(new java.awt.Dimension(915, 322));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_0.setText("0");
        btn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_0ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 165, 45));

        btn_1.setLabel("1");
        btn_1.setMaximumSize(new java.awt.Dimension(45, 45));
        btn_1.setMinimumSize(new java.awt.Dimension(45, 45));
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 45, 45));

        btn_2.setText("2");
        btn_2.setMaximumSize(new java.awt.Dimension(45, 45));
        btn_2.setMinimumSize(new java.awt.Dimension(45, 45));
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 45, 45));

        btn_3.setText("3");
        btn_3.setMaximumSize(new java.awt.Dimension(45, 45));
        btn_3.setMinimumSize(new java.awt.Dimension(45, 45));
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 45, 45));

        btn_4.setText("4");
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 45, 45));

        btn_5.setText("5");
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 45, 45));

        btn_6.setText("6");
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 45, 45));

        btn_7.setText("7");
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 45, 45));

        btn_8.setText("8");
        btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 45, 45));

        btn_9.setText("9");
        btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 45, 45));

        btn_A.setText("A");
        btn_A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AActionPerformed(evt);
            }
        });
        getContentPane().add(btn_A, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 45, 45));

        btn_C.setText("C");
        btn_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CActionPerformed(evt);
            }
        });
        getContentPane().add(btn_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 45, 45));

        btn_B.setText("B");
        btn_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BActionPerformed(evt);
            }
        });
        getContentPane().add(btn_B, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 45, 45));

        btn_D.setText("D");
        btn_D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DActionPerformed(evt);
            }
        });
        getContentPane().add(btn_D, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 45, 45));

        btn_E.setText("E");
        btn_E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EActionPerformed(evt);
            }
        });
        getContentPane().add(btn_E, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 45, 45));

        btn_F.setText("F");
        btn_F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FActionPerformed(evt);
            }
        });
        getContentPane().add(btn_F, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 45, 45));

        btn_Equal.setText("=");
        btn_Equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EqualActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Equal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 45, 45));

        btn_Clear.setText("CE");
        btn_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClearActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 45, 45));

        btn_division.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_division.setText("/");
        btn_division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_divisionActionPerformed(evt);
            }
        });
        getContentPane().add(btn_division, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 45, 45));

        btn_multiplicacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_multiplicacion.setText("*");
        btn_multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_multiplicacionActionPerformed(evt);
            }
        });
        getContentPane().add(btn_multiplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 45, 45));

        btn_resta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_resta.setText("-");
        btn_resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_restaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_resta, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 45, 45));

        btn_Suma.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_Suma.setText("+");
        btn_Suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SumaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Suma, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 45, 105));

        lbl_Dec.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lbl_Dec.setText("0");
        getContentPane().add(lbl_Dec, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 122, -1, -1));

        lbl_Bin.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lbl_Bin.setText("0");
        getContentPane().add(lbl_Bin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 182, -1, -1));

        lbl_Oct.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lbl_Oct.setText("0");
        getContentPane().add(lbl_Oct, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 162, -1, -1));

        lbl_Hex.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lbl_Hex.setText("0");
        getContentPane().add(lbl_Hex, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 142, -1, -1));

        btnGrp_Sistema.add(rBtn_Dec);
        rBtn_Dec.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        rBtn_Dec.setSelected(true);
        rBtn_Dec.setText("DEC:");
        rBtn_Dec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtn_DecActionPerformed(evt);
            }
        });
        getContentPane().add(rBtn_Dec, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        btnGrp_Sistema.add(rBtn_Hex);
        rBtn_Hex.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        rBtn_Hex.setText("HEX:");
        rBtn_Hex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtn_HexActionPerformed(evt);
            }
        });
        getContentPane().add(rBtn_Hex, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        btnGrp_Sistema.add(rBtn_Oct);
        rBtn_Oct.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        rBtn_Oct.setText("OCT:");
        rBtn_Oct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtn_OctActionPerformed(evt);
            }
        });
        getContentPane().add(rBtn_Oct, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        btnGrp_Sistema.add(rBtn_Bin);
        rBtn_Bin.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        rBtn_Bin.setText("BIN:");
        rBtn_Bin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtn_BinActionPerformed(evt);
            }
        });
        getContentPane().add(rBtn_Bin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        lbl_resultado.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lbl_resultado.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbl_resultado.setText("0");
        lbl_resultado.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lbl_resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 290, 90));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rBtn_HexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtn_HexActionPerformed
        // TODO add your handling code here:
        enableHex();
        lbl_resultado.setText(hex);
        
        flag = 2;
        info = "";
    }//GEN-LAST:event_rBtn_HexActionPerformed

    private void rBtn_DecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtn_DecActionPerformed
        // TODO add your handling code here:
        enableDec();
        disableHex();
        lbl_resultado.setText(dec);
        
        flag = 1;
        info = "";
    }//GEN-LAST:event_rBtn_DecActionPerformed

    private void rBtn_OctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtn_OctActionPerformed
        // TODO add your handling code here:
        disableHex();
        enableOct();
        lbl_resultado.setText(oct);
        
        flag = 3;
        info = "";
    }//GEN-LAST:event_rBtn_OctActionPerformed

    private void rBtn_BinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtn_BinActionPerformed
        // TODO add your handling code here:
        enableBin();
        lbl_resultado.setText(bin);
        
        flag = 4;
        info = "";
    }//GEN-LAST:event_rBtn_BinActionPerformed

    private void btn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_0ActionPerformed
        // TODO add your handling code here:
        getInfo(btn_0.getText());
        readFlag(flag, setInfo());
        lbl_resultado.setText(setInfo());
    }//GEN-LAST:event_btn_0ActionPerformed

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
        // TODO add your handling code here:
        getInfo(btn_1.getText());
        readFlag(flag, setInfo());
        lbl_resultado.setText(setInfo());
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
        // TODO add your handling code here:
        getInfo(btn_2.getText());
        readFlag(flag, setInfo());
        lbl_resultado.setText(setInfo());
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
        // TODO add your handling code here:
        getInfo(btn_3.getText());
        readFlag(flag, setInfo());
        lbl_resultado.setText(setInfo());
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
        // TODO add your handling code here:
        getInfo(btn_4.getText());
        readFlag(flag, setInfo());
        lbl_resultado.setText(setInfo());

    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
        // TODO add your handling code here:
        getInfo(btn_5.getText());
        readFlag(flag, setInfo());
        lbl_resultado.setText(setInfo());
    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
        // TODO add your handling code here:
        getInfo(btn_6.getText());
        readFlag(flag, setInfo());
        lbl_resultado.setText(setInfo());
    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
        // TODO add your handling code here:
        getInfo(btn_7.getText());
        readFlag(flag, setInfo());
        lbl_resultado.setText(setInfo());
    }//GEN-LAST:event_btn_7ActionPerformed

    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
        // TODO add your handling code here:
        getInfo(btn_8.getText());
        readFlag(flag, setInfo());
        lbl_resultado.setText(setInfo());
    }//GEN-LAST:event_btn_8ActionPerformed

    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
        // TODO add your handling code here:
        getInfo(btn_9.getText());
        readFlag(flag, setInfo());
        lbl_resultado.setText(setInfo());
    }//GEN-LAST:event_btn_9ActionPerformed

    private void btn_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AActionPerformed
        // TODO add your handling code here:
        getInfo(btn_A.getText());
        readFlag(flag, setInfo());
        lbl_resultado.setText(setInfo());
    }//GEN-LAST:event_btn_AActionPerformed

    private void btn_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BActionPerformed
        // TODO add your handling code here:
        getInfo(btn_B.getText());
        readFlag(flag, setInfo());
        lbl_resultado.setText(setInfo());
    }//GEN-LAST:event_btn_BActionPerformed

    private void btn_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CActionPerformed
        // TODO add your handling code here:
        getInfo(btn_C.getText());
        readFlag(flag, setInfo());
        lbl_resultado.setText(setInfo());
    }//GEN-LAST:event_btn_CActionPerformed

    private void btn_DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DActionPerformed
        // TODO add your handling code here:
        getInfo(btn_D.getText());
        readFlag(flag, setInfo());
        lbl_resultado.setText(setInfo());
    }//GEN-LAST:event_btn_DActionPerformed

    private void btn_EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EActionPerformed
        // TODO add your handling code here:
        getInfo(btn_C.getText());
        readFlag(flag, setInfo());
        lbl_resultado.setText(setInfo());
    }//GEN-LAST:event_btn_EActionPerformed

    private void btn_FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FActionPerformed
        // TODO add your handling code here:
        getInfo(btn_D.getText());
        readFlag(flag, setInfo());
        lbl_resultado.setText(setInfo());
    }//GEN-LAST:event_btn_FActionPerformed

    private void btn_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClearActionPerformed
        // TODO add your handling code here:
        erease();
    }//GEN-LAST:event_btn_ClearActionPerformed

    private void btn_SumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SumaActionPerformed
        // TODO add your handling code here:
        
        op = btn_Suma.getText();
        resultado = dec;
        erease();

    }//GEN-LAST:event_btn_SumaActionPerformed

    private void btn_EqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EqualActionPerformed
        // TODO add your handling code here:

        info = "";
        
        readFlag(flag, operacion(dec, op));

        getBinary(dec);
        getHexa(dec);
        getOctal(dec);

        
        getInfo(lbl_resultado.getText());

    }//GEN-LAST:event_btn_EqualActionPerformed

    private void btn_multiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multiplicacionActionPerformed
        // TODO add your handling code here:
        
        op = btn_multiplicacion.getText();
        resultado = dec;
        erease();
    }//GEN-LAST:event_btn_multiplicacionActionPerformed

    private void btn_divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divisionActionPerformed
        // TODO add your handling code here:
        op = btn_division.getText();
        resultado = dec;
        erease();
    }//GEN-LAST:event_btn_divisionActionPerformed

    private void btn_restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restaActionPerformed
        // TODO add your handling code here:
        op = btn_resta.getText();
        resultado = dec;
        erease();
    }//GEN-LAST:event_btn_restaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadora().setVisible(true);
            }
        });
    }

////////////////////////////////////////////////////////////////////////////////
    //CODIGO//
////////////////////////////////////////////////////////////////////////////////
    public String dec = "",
            bin = "",
            hex = "",
            oct = "",
            info = "",
            resultado = "",
            op = "";

    public int flag;

    public void erease() {

        lbl_resultado.setText("0");
        lbl_Dec.setText("0");
        lbl_Bin.setText("0");
        lbl_Oct.setText("0");
        lbl_Hex.setText("0");
        dec = "";
        bin = "";
        hex = "";
        oct = "";
        info = "";
    }

//============================ACTIVAR / DESCATIVAR============================//
//=================================BOTONES====================================//  
    /*HABILITAR HEXA*/
    public void enableHex() {

        enableDec();
        btn_A.setEnabled(true);
        btn_B.setEnabled(true);
        btn_C.setEnabled(true);
        btn_D.setEnabled(true);
        btn_E.setEnabled(true);
        btn_F.setEnabled(true);

    }

    /*DESHABILITAR HEXA*/
    public void disableHex() {

        btn_A.setEnabled(false);
        btn_B.setEnabled(false);
        btn_C.setEnabled(false);
        btn_D.setEnabled(false);
        btn_E.setEnabled(false);
        btn_F.setEnabled(false);

    }

    /*DESHABILITAR DEC*/
    public void disableDec() {

        btn_2.setEnabled(false);
        btn_3.setEnabled(false);
        btn_4.setEnabled(false);
        btn_5.setEnabled(false);
        btn_6.setEnabled(false);
        btn_7.setEnabled(false);
        btn_8.setEnabled(false);
        btn_9.setEnabled(false);

    }

    /*HABILITAR DEC*/
    public void enableDec() {

        disableHex();
        btn_2.setEnabled(true);
        btn_3.setEnabled(true);
        btn_4.setEnabled(true);
        btn_5.setEnabled(true);
        btn_6.setEnabled(true);
        btn_7.setEnabled(true);
        btn_8.setEnabled(true);
        btn_9.setEnabled(true);

    }

    /*HABILITAR BIN*/
    public void enableBin() {

        disableDec();
        disableHex();
    }

    /*HABILITAR OCT*/
    public void enableOct() {

        enableDec();
        disableHex();
        btn_8.setEnabled(false);
        btn_9.setEnabled(false);
    }

//======================MOSTRAR EN SU RESPECTIVO SISTEMA======================//

    /*GUARDAR DATOS*/ //POR LO MIENTRAS DECIMAL
    public void getInfo(String Dec) {
        info += Dec;
    }

    public String setInfo() {

        return info;
    }

    /*CONVERTIR A BINARIO*/
    public void getBinary(String Dec) {

        int i = Integer.valueOf(Dec);

        bin = Integer.toBinaryString(i);

        lbl_Bin.setText(bin);
    }

    /*CONVERTIR A OCTAL*/
    public void getOctal(String Dec) {

        int i = Integer.valueOf(Dec);

        oct = Integer.toOctalString(i);

        lbl_Oct.setText(oct);
    }

    /*CONVERTIR A HEXADECIMAL*/
    public void getHexa(String Dec) {

        int i = Integer.valueOf(Dec);

        hex = Integer.toHexString(i);

        lbl_Hex.setText(hex);
    }

    /*CONVERTIR A DEC*/
    public void getDec(String Dec, int i) {
        switch (i) {
            case 2:
                dec = Integer.toString(Integer.parseInt(Dec, i));
                lbl_Dec.setText(dec);
                break;
            case 8:
                dec = Integer.toString(Integer.parseInt(Dec, i));
                lbl_Dec.setText(dec);
                break;
            case 16:
                dec = Integer.toString(Integer.parseInt(Dec, i));
                lbl_Dec.setText(dec);
                break;
            default:
                dec = Dec;
                lbl_Dec.setText(dec);
        }
    }

    /*===========================SELECTOR DE SISTEMAS=============================*/
 /*Información acerca de los valores de flag
                  1 - DEC | 2 - HEX | 3 - OCT | 4 - BIN*/
 /*============================================================================*/
    public void readFlag(int flg, String a) {
        switch (flg) {
            case 1:                
               
                getDec(a, 0);
                                
                getBinary(dec);
                getOctal(dec);
                getHexa(dec);

                                
                break;
                
            case 2:
                               
                getDec(a, 16);

                getBinary(dec);
                getOctal(dec);
                getHexa(dec);
                
                break;
                
                
                
            case 3:
                                
                getDec(a, 8);

                getBinary(dec);
                getOctal(dec);
                getHexa(dec);

                break;
                
            case 4:
                                
                getDec(a, 2);

                getBinary(dec);
                getOctal(dec);
                getHexa(dec);

                break;
        }
    }

    /*OPERACIONES*/
    public String operacion(String n, String o) {

        int n1 = Integer.valueOf(dec);

        switch (o) {
            case "+":

                n1 += Integer.valueOf(resultado);

                resultado = Integer.toString(n1);

                break;
            case "-":
                n1 = Integer.valueOf(resultado)-n1;

                resultado = Integer.toString(n1);
                break;
            case "*":
                n1 *= Integer.valueOf(resultado);

                resultado = Integer.toString(n1);
                break;
            case "/":
                n1 /= Integer.valueOf(resultado);

                resultado = Integer.toString(n1);
                break;
        }

        return resultado;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrp_Sistema;
    private javax.swing.JButton btn_0;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton btn_A;
    private javax.swing.JButton btn_B;
    private javax.swing.JButton btn_C;
    private javax.swing.JButton btn_Clear;
    private javax.swing.JButton btn_D;
    private javax.swing.JButton btn_E;
    private javax.swing.JButton btn_Equal;
    private javax.swing.JButton btn_F;
    private javax.swing.JButton btn_Suma;
    private javax.swing.JButton btn_division;
    private javax.swing.JButton btn_multiplicacion;
    private javax.swing.JButton btn_resta;
    private javax.swing.JLabel lbl_Bin;
    private javax.swing.JLabel lbl_Dec;
    private javax.swing.JLabel lbl_Hex;
    private javax.swing.JLabel lbl_Oct;
    private javax.swing.JLabel lbl_resultado;
    private javax.swing.JRadioButton rBtn_Bin;
    private javax.swing.JRadioButton rBtn_Dec;
    private javax.swing.JRadioButton rBtn_Hex;
    private javax.swing.JRadioButton rBtn_Oct;
    // End of variables declaration//GEN-END:variables
}
